{"name": "При создании пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "start": 1716882328431, "stop": 1716882328787, "uuid": "9730e224-7d4c-49ae-8303-162c34c7bc5c", "historyId": "a735a2e6ba3523298e20ac984a61e552", "testCaseId": "a735a2e6ba3523298e20ac984a61e552", "fullName": "tests.test_create_courier#test_create_same_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "host", "value": "MBP-Olga"}, {"name": "thread", "value": "5325-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}