{"name": "Если создаем курьера без логина, возвращается ошибка", "status": "passed", "start": 1716882329356, "stop": 1716882329462, "uuid": "72025773-2b03-4224-bfc8-d10c450681f6", "historyId": "c1ea846b0f5ca504f01b64e6f85297a9", "testCaseId": "c1ea846b0f5ca504f01b64e6f85297a9", "fullName": "tests.test_create_courier#test_message_create_courier_without_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "host", "value": "MBP-Olga"}, {"name": "thread", "value": "5325-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}